---
- name: Remove any nginx packages
  dnf:
    name: nginx
    state: absent

- name: Install dnf-utils
  dnf:
    name: dnf-utils
    state: present

- name: Add nginx latest repo
  copy:
    src: files/nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: Install nginx
  dnf: 
    name: nginx 
    state: present

- name: Start nginx
  service: name=nginx state=started

- name: Configure nginx site
  template:
    src: files/default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx reloaded