---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  handlers:
    - include: handlers.yml

  tasks:
    - name: Run preamble playbooks
      include: open_ports.yml

    - name: Run php playbook
      include: php_install.yml

    - name: Run nginx playbook
      include: nginx_playbook.yml

    - name: Run mysql playbook
      include: mariadb_install.yml

    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www"
        remote_src: yes
        creates: "{{ wordpress_directory }}"

    - name: Set permissions on wordpress directory
      file:
        path: "{{ wordpress_directory }}"
        state: directory
        recurse: yes
        mode: 0755
        owner: nginx
        group: nginx

    - name: Copy WordPress configuration
      template:
        src: files/wp-config.php.j2
        dest: "{{ wordpress_directory }}/wp-config.php"

    - name: Change permissions on wp-content directory
      file:
        path: "{{ wordpress_directory }}/wp-content/plugins"
        state: directory
        recurse: yes
        mode: 0777
        owner: nginx

    - debug: var=hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address']