- include_tasks: setup-Debian.yml
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20") # Only Ubuntu 20.04

- include_tasks: setup-Centos.yml
  when: ansible_facts['distribution'] == "CentOS" # CentOS 8,7,6