---
# tasks file for open_ports
- name: Disabling SELinux
  selinux:
    state: disabled

- name: Install firewall
  package:
    name: 
      - firewalld
      - curl
      - unzip 
    state: latest
    update_cache: yes

- name: Configure firewall
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Enable http on firewall
  firewalld:
    service: http
    zone: public
    permanent: yes
    state: enabled
    immediate: yes
  notify:
    - Reload firewall

- name: Enable https on firewall
  firewalld:
    service: https
    zone: public
    permanent: yes
    immediate: yes
    state: enabled