---
# vars file for mariadb
wordpress_db_name: "wordpress_db"
wordpress_db_user: "wordpress"
wordpress_db_password: "secretpassword"
mysql_root_user: root
mysql_root_password: "secretpassword"
login_password: secretpassword
# new_mysql_root_user: wordpress